name: deepcemv2
channels:
  - defaults
  - conda-forge
dependencies:
  - aiodns=3.5.0=py311hca03da5_1
  - aiohappyeyeballs=2.6.1=py311hca03da5_0
  - aiohttp=3.13.2=py311haa24f5a_0
  - aiosignal=1.4.0=py311hca03da5_0
  - annotated-types=0.6.0=py311hca03da5_1
  - anyio=4.10.0=py311hca03da5_0
  - arrow-cpp=21.0.0=h9e9184e_1
  - attrs=25.4.0=py311hca03da5_2
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311h03d0aa3_1
  - brotlicffi=1.2.0.0=py311h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.12.2=hca03da5_0
  - catalogue=2.0.10=py311hca03da5_0
  - certifi=2025.11.12=py311hca03da5_0
  - cffi=2.0.0=py311h73c2a22_1
  - charset-normalizer=3.4.4=py311hca03da5_0
  - click=8.2.1=py311hca03da5_1
  - cloudpathlib=0.21.0=py311hca03da5_0
  - cloudpickle=3.1.2=py311hca03da5_0
  - colorama=0.4.6=py311hca03da5_0
  - confection=0.1.5=py311hd096484_0
  - cymem=2.0.11=py311h0962b89_0
  - cython-blis=1.0.1=py311h80987f9_0
  - datasets=4.4.1=py311hca03da5_0
  - dill=0.4.0=py311hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - filelock=3.20.0=py311hca03da5_0
  - frozenlist=1.8.0=py311h50f4ffc_0
  - fsspec=2025.10.0=py311h7eb115d_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - glog=0.5.0=h313beb8_1
  - h11=0.16.0=py311hca03da5_1
  - hf-xet=1.1.8=py311h8cd5084_0
  - httpcore=1.0.9=py311hca03da5_0
  - httpx=0.28.1=py311hca03da5_1
  - huggingface_hub=0.34.4=py311hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.11=py311hca03da5_0
  - jansson=2.14=h80987f9_1
  - jinja2=3.1.6=py311hca03da5_0
  - joblib=1.5.2=py311hca03da5_0
  - jsonlines=4.0.0=py311hca03da5_0
  - langcodes=3.5.0=py311hca03da5_0
  - language-data=1.3.0=py311hca03da5_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libgrpc=1.71.0=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_2
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.22.0=hbe873a3_0
  - libunistring=1.3=h1799b2a_0
  - libuv=1.48.0=h80987f9_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - marisa-trie=1.3.1=py311h0962b89_0
  - markdown-it-py=4.0.0=py311hca03da5_0
  - markupsafe=3.0.2=py311h80987f9_0
  - mdurl=0.1.2=py311hca03da5_0
  - multidict=6.7.0=py311h254cc4a_0
  - multiprocess=0.70.18=py311hca03da5_0
  - murmurhash=1.0.15=py311h00ad4d8_0
  - ncurses=6.5=hee39554_0
  - nltk=3.9.2=py311h661b90a_0
  - numexpr=2.14.1=py311h5fbe615_0
  - numpy=2.3.5=py311h4bb6f22_0
  - numpy-base=2.3.5=py311h23175f9_0
  - openssl=3.0.18=h9b4081a_0
  - orc=2.2.0=hec253e6_0
  - packaging=25.0=py311hca03da5_1
  - pandas=2.3.3=py311h3f644e9_1
  - pip=25.3=pyhc872135_0
  - preshed=3.0.9=py311h313beb8_0
  - propcache=0.4.1=py311haa24f5a_0
  - protobuf=5.29.3=py311h514c7bf_0
  - pyarrow=21.0.0=py311h3f644e9_1
  - pycares=4.10.0=py311h091efcb_0
  - pycparser=2.23=py311hca03da5_0
  - pydantic=2.12.4=py311hca03da5_0
  - pydantic-core=2.41.5=py311h931abed_1
  - pygments=2.19.2=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_1
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h80987f9_0
  - pytz=2025.2=py311hca03da5_0
  - pyyaml=6.0.3=py311h091b9d3_0
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h0b18652_0
  - regex=2025.11.3=py311haa24f5a_0
  - requests=2.32.5=py311hca03da5_1
  - rich=13.9.4=py311hca03da5_0
  - ruamel_yaml=0.17.21=py311h80987f9_0
  - safetensors=0.6.2=py311h931abed_0
  - scikit-learn=1.7.2=py311h3f644e9_1
  - scipy=1.16.3=py311h08a1045_0
  - setuptools=80.9.0=py311hca03da5_0
  - shellingham=1.5.4=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - smart_open=7.3.1=py311hca03da5_0
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.1=py311hca03da5_0
  - spacy=3.8.2=py311h48ca7d4_0
  - spacy-legacy=3.0.12=py311hca03da5_0
  - spacy-loggers=1.0.4=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - srsly=2.5.2=py311h50f4ffc_0
  - tensorboardx=2.6.4=py311hca03da5_0
  - thinc=8.3.2=py311h48ca7d4_1
  - threadpoolctl=3.5.0=py311h7eb115d_1
  - tk=8.6.15=hcd8a7d5_0
  - tokenizers=0.21.0=py311hac6c8b7_0
  - tqdm=4.67.1=py311h7eb115d_1
  - transformers=4.49.0=py311hca03da5_0
  - typer=0.9.0=py311hca03da5_0
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing-inspection=0.4.2=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - ujson=5.11.0=py311h50f4ffc_0
  - urllib3=2.6.1=py311hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - uvloop=0.22.1=py311h8e34c70_1
  - wasabi=1.1.3=py311hca03da5_0
  - weasel=0.4.1=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - wrapt=2.0.1=py311haa24f5a_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.22.0=py311haa24f5a_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/anaconda3/envs/deepcemv2
